more experiments getting this started

diff --git a/config.dist/gunicorn b/config.dist/gunicorn
--- a/config.dist/gunicorn
+++ b/config.dist/gunicorn
@@ -24,7 +24,7 @@ start()
 {
     echo "Starting $NAME."
     export PYTHONPATH=$CONFDIR:/root/.virtualenvs/python2.6/site-packages;
-    "workon mycelium; python manage.py $GUNICORN_RUN -b localhost:$PORT -n $NAME -w $WORKERS -p $PID -D envs.live --daemon" && echo "OK" || echo "failed";
+    "workon mycelium; python manage.py $GUNICORN_RUN  -workers=$WORKERS -p $PID --settings=envs.live --daemon" && echo "OK" || echo "failed";
 }
 
 stop()
