config tweak

diff --git a/config.dist/gunicorn b/config.dist/gunicorn
--- a/config.dist/gunicorn
+++ b/config.dist/gunicorn
@@ -24,7 +24,7 @@ start()
 {
     echo "Starting $NAME."
     export PYTHONPATH=$CONFDIR:/root/.virtualenvs/python2.6/site-packages;
-    "workon mycelium; /root/.virtualenvs/mycelium/bin/python2.6 manage.py $GUNICORN_RUN  -workers=$WORKERS -p $PID --settings=envs.live --daemon" && echo "OK" || echo "failed";
+    "/root/.virtualenvs/mycelium/bin/python2.6 /var/www/mycelium.git/mycelium/manage.py $GUNICORN_RUN  -workers=$WORKERS -p $PID --settings=envs.live --daemon" && echo "OK" || echo "failed";
 }
 
 stop()
